server:
  port: 8080

#Thymeleaf缓存在开发过程中，肯定是不行的，那么就要在开发的时候把缓存关闭，只需要在application.properties进行配置即可
spring:
  thymeleaf:
#    使用thymeleaf模板一定要配置此项，否则在项目打包为jar时会访问不到template下的html文件
#    打包使用LifeCycle下的组件进行打包，先clean，再install
    prefix: classpath:/templates
#    suffix: html
#    mode: HTML5
#    encoding: UTF-8
#    content-type: text/html
    cache: false

  #配置jsp
#  在src/main/resources/application.properties文件中配置JSP和传统Spring MVC中和view的关联
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /WEB-INF/jsp
      # 响应页面默认后缀
      suffix: .jsp
  ########################################################
  ###datasource  配置MySQL数据源；
  ########################################################
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  ########################################################
  ###REDIS (RedisProperties) redis基本配置；
  ########################################################
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
  ########################################################
  ### Java Persistence Api 自动进行建表
  ########################################################
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

  ########################################################
  ###mail setting
  ########################################################

  mail:
  # 设置邮箱主机,以qq邮箱为例
    host: smtp.163.com
    port:
    # 设置用户名
    username: 13895167943@163.com
    # 设置密码
    password: 31181993xyz
    properties:
      mail:
        smtp:
          # 设置是否需要认证，如果为true,那么用户名和密码就必须的，
          #如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
          auth: true
          # STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信
          starttls:
            enable: true
            required: true


application:
  # 自定义属性，可以在Controller中读取
  hello: hello GOD

info:
  app:
    name: ecs
    version: 1.0.0
  build:
    artifactId: @project.artifactId@
    version: @project.version@

logging:
  level: debug


